CREATE TABLE Users (
    UserID INT64 NOT NULL,
    Type INT64 NOT NULL,
    Name STRING(100) NOT NULL,
    Email STRING(100) NOT NULL,
    Password STRING(100) NOT NULL,
) PRIMARY KEY(UserID);

CREATE TABLE Posts (
    PostID INT64 NOT NULL,
    Title STRING(MAX) NOT NULL,
    Content STRING(MAX) NOT NULL,
    Attachments ARRAY<STRING(MAX)> NOT NULL
) PRIMARY KEY(UserID, PostID),
  INTERLEAVE IN PARENT Users ON DELETE CASCADE;